<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "zahnstocher"
 *
 * Auto generated by Extension Builder 2015-11-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Zahnstocher',
	'description' => 'Zahnstocher (en. toothpick) helps you when piercing into programming code.',
	'category' => 'misc',
	'author' => 'Steffen Müller',
	'author_email' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-8.7.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
